# GitLab CI/CD configuration for building a Maven Java project and Docker image

stages:
  - build
  - docker

maven-build:
  image: maven:3.9.6-eclipse-temurin-21
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/robot-world-0.0.2.jar
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.m2/repository
  rules:
    - exists:
        - pom.xml

docker-build:
  image: docker:cli
  stage: docker
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
        - pom.xml
        - target/robot-world-0.0.2.jar